config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'players#index'
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		# @player = Player.first
		@players = Player.all
	end

	def new
		@player = Player.new
	end

	def create
		Player.create(player_params)
		redirect_to root_path
	end

	private

	def player_params
		params.require(:player).permit(:player, :tour, :email, :quota)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Players</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        Golfweek Amateur Tour
      </div>
      <div class="col-4">
        Points Game Players
      </div>
      <div class="col-5">
        <%= link_to 'Add Player', new_player_path %>
      </div>
    </header>

    <br class="clear" />

    <%= yield %>

  </body>
</html>

app/views/players/index.html.erb
<h1>All Players</h1>

<% @players.each do |player| %>
	<%= player.player %>
	</br>
<%end%>

app/views/players/new.html.erb
<h1>Enter New Player Detail</h1>
<%= simple_form_for @player do |f| %>
	<%= f.input :player %>
	<%= f.input :tour %>
	<%= f.input :email %>
	<%= f.input :quota %>
	</br>
	<%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>